// <auto-generated />
using System;
using Emanate.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Emanate.Web.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20190628043614_RenameDeviceProfiles")]
    partial class RenameDeviceProfiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Emanate.Web.Model.DisplayDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DisplayDevices");
                });

            modelBuilder.Entity("Emanate.Web.Model.DisplayDeviceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DisplayDeviceProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
